# Generated by Django 5.2.5 on 2025-08-11 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consulta',
            options={'ordering': ['-data_hora']},
        ),
        migrations.RenameField(
            model_name='medico',
            old_name='usuario',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='usuario',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='diagnostico',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='prescricao',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='telefone',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='endereco',
        ),
    ]
