# Generated by Django 5.2.4 on 2025-08-12 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='logradouro',
            new_name='rua',
        ),
    ]
