# Generated by Django 5.2.4 on 2025-08-12 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='apelido',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
